version: "3.5"

services:
  mongo:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/docker/mongo/data:/data/db
    networks:
      - mongonet
  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    networks:
      - mongonet

networks:
  mongonet: